algoritmo "Exercicio 7"
// Função :
// Autor :
// Data : 27/09/2022
// Seção de Declarações 
var
i,x, aux: inteiro
n : vetor [0..199] de inteiro
result: vetor [0..199] de inteiro
inicio
escreva("Digite a quantidade de alunos: ")
leia(x)

se (x >= 1) E (x >= 200) entao
   para i de 1 ate x passo 1 faca
   escreva ("Digite a nota do aluno: ")
   leia(x)
        aux:= n[i] = n[i]
        result[i]<- result[i] + 1

   fimpara

fimse


fimalgoritmo
