Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/09/2022
Var
// Seção de Declarações das variáveis 
fat, i, n:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Digite o numero: ")
leia(n)

fat <- 1
i<-1

enquanto (i<=n) faca
 fat <- fat*i
 i <- i+1
fimenquanto

escreval ("A fatorial é: ", fat)

Fimalgoritmo